create table employee (
	id INT,
	name VARCHAR(50),
	birthday DATE,
	email VARCHAR(100)
);

-- dataset generated by "https://www.mockaroo.com/"

insert into employee (id, name, birthday, email) values (1, 'Jewel Joder', '11/24/1991', 'jjoder0@tinyurl.com');
insert into employee (id, name, birthday, email) values (2, 'Howard Simonsen', '5/5/1983', 'hsimonsen1@aboutads.info');
insert into employee (id, name, birthday, email) values (3, 'Clark Silverstone', '5/10/2017', 'csilverstone2@delicious.com');
insert into employee (id, name, birthday, email) values (4, 'Gare Pol', '2/11/1993', 'gpol3@4shared.com');
insert into employee (id, name, birthday, email) values (5, 'Noemi Corish', '1/5/1988', 'ncorish4@surveymonkey.com');
insert into employee (id, name, birthday, email) values (6, 'Bell Soro', '10/1/1992', 'bsoro5@tuttocitta.it');
insert into employee (id, name, birthday, email) values (7, 'Hugibert Scheffel', '7/11/1963', 'hscheffel6@virginia.edu');
insert into employee (id, name, birthday, email) values (8, 'Cos Glenton', '8/4/2004', 'cglenton7@parallels.com');
insert into employee (id, name, birthday, email) values (9, 'Chloette Jell', '9/10/1971', 'cjell8@bloomberg.com');
insert into employee (id, name, birthday, email) values (10, 'Francklyn Collick', '11/4/2009', 'fcollick9@ft.com');
insert into employee (id, name, birthday, email) values (11, 'Bobbye Libri', '2/19/2001', 'blibria@mediafire.com');
insert into employee (id, name, birthday, email) values (12, 'Nydia Leverentz', '12/18/2008', 'nleverentzb@google.de');
insert into employee (id, name, birthday, email) values (13, 'Jemmy Maving', '11/18/1970', 'jmavingc@accuweather.com');
insert into employee (id, name, birthday, email) values (14, 'Evered Melding', '1/15/1954', 'emeldingd@telegraph.co.uk');
insert into employee (id, name, birthday, email) values (15, 'Gerik Poate', '3/8/2013', 'gpoatee@shop-pro.jp');
insert into employee (id, name, birthday, email) values (16, 'Maridel Twiddle', '2/2/1985', 'mtwiddlef@uol.com.br');
insert into employee (id, name, birthday, email) values (17, 'Mariya Maps', '9/11/1961', 'mmapsg@geocities.com');
insert into employee (id, name, birthday, email) values (18, 'Francine Kondratovich', '2/5/1985', 'fkondratovichh@typepad.com');
insert into employee (id, name, birthday, email) values (19, 'Michel Lyes', '4/22/1996', 'mlyesi@livejournal.com');
insert into employee (id, name, birthday, email) values (20, 'Sibbie Dallimore', '6/6/1976', 'sdallimorej@ebay.co.uk');
insert into employee (id, name, birthday, email) values (21, 'Fanni Giacubbo', '12/12/1962', 'fgiacubbok@123-reg.co.uk');
insert into employee (id, name, birthday, email) values (22, 'Evelyn Hainning', '5/28/1983', 'ehainningl@accuweather.com');
insert into employee (id, name, birthday, email) values (23, 'Manon Pickle', '5/15/1990', 'mpicklem@mail.ru');
insert into employee (id, name, birthday, email) values (24, 'Krispin Kremer', '3/6/1982', 'kkremern@nasa.gov');
insert into employee (id, name, birthday, email) values (25, 'Morten Leggatt', '1/28/1958', 'mleggatto@nasa.gov');
insert into employee (id, name, birthday, email) values (26, 'Valentijn Veillard', '2/18/1953', 'vveillardp@angelfire.com');
insert into employee (id, name, birthday, email) values (27, 'Twila Gillet', '8/26/1975', 'tgilletq@go.com');
insert into employee (id, name, birthday, email) values (28, 'Betteann Niesegen', '3/9/2005', 'bniesegenr@quantcast.com');
insert into employee (id, name, birthday, email) values (29, 'Cleon Eamer', '11/25/2013', 'ceamers@shinystat.com');
insert into employee (id, name, birthday, email) values (30, 'Arri Ewin', '4/16/1956', 'aewint@wiley.com');
insert into employee (id, name, birthday, email) values (31, 'Jose Rouke', '4/7/1982', 'jroukeu@multiply.com');
insert into employee (id, name, birthday, email) values (32, 'Dorey Youthead', '1/24/2001', 'dyoutheadv@bing.com');
insert into employee (id, name, birthday, email) values (33, 'Ermina Bednall', '5/22/2023', 'ebednallw@whitehouse.gov');
insert into employee (id, name, birthday, email) values (34, 'Minny Pidgeley', '6/18/2020', 'mpidgeleyx@symantec.com');
insert into employee (id, name, birthday, email) values (35, 'Latrina Serris', '9/28/1960', 'lserrisy@yahoo.co.jp');
insert into employee (id, name, birthday, email) values (36, 'Inga Wasylkiewicz', '8/31/1970', 'iwasylkiewiczz@g.co');
insert into employee (id, name, birthday, email) values (37, 'Benedikt Carwithen', '5/13/2012', 'bcarwithen10@clickbank.net');
insert into employee (id, name, birthday, email) values (38, 'Enriqueta Klageman', '12/28/1991', 'eklageman11@huffingtonpost.com');
insert into employee (id, name, birthday, email) values (39, 'Tania Alvarez', '1/20/1997', 'talvarez12@google.ru');
insert into employee (id, name, birthday, email) values (40, 'Nadia Mac Geaney', '3/4/2001', 'nmac13@wikipedia.org');
insert into employee (id, name, birthday, email) values (41, 'Jervis Pizer', '2/13/2015', 'jpizer14@free.fr');
insert into employee (id, name, birthday, email) values (42, 'Erl Dowdle', '7/18/1955', 'edowdle15@admin.ch');
insert into employee (id, name, birthday, email) values (43, 'Arlin Tofpik', '3/23/1988', 'atofpik16@icio.us');
insert into employee (id, name, birthday, email) values (44, 'Ted Braemer', '3/12/1988', 'tbraemer17@webs.com');
insert into employee (id, name, birthday, email) values (45, 'Jeno Mundow', '10/17/2001', 'jmundow18@theatlantic.com');
insert into employee (id, name, birthday, email) values (46, 'Mandy Pursglove', '12/18/1984', 'mpursglove19@thetimes.co.uk');
insert into employee (id, name, birthday, email) values (47, 'Alethea Antonietti', '3/26/1969', 'aantonietti1a@jugem.jp');
insert into employee (id, name, birthday, email) values (48, 'Towney Mazin', '12/3/1983', 'tmazin1b@irs.gov');
insert into employee (id, name, birthday, email) values (49, 'Karel Ganiford', '7/22/1976', 'kganiford1c@telegraph.co.uk');
insert into employee (id, name, birthday, email) values (50, 'Lorrin Cettell', '3/5/1976', 'lcettell1d@theglobeandmail.com');


-- select * from employee;

-- 5 update operations
update employee set name = 'Jane Doe' where id = 10;
update employee set birthday = '1999-09-09' where id = 20;
update employee set email = 'aewin@gmail.com' where id = 30;
update employee set id = 51 where name = 'Morten Leggatt';
update employee set name = 'Hugh Scheffel' where id=7;

-- 5 delete operations
delete from employee where email = 'lcettell1d@theglobeandmail.com';
delete from employee where name = 'Alethea Antonietti';
delete from employee where id = 49;
delete from employee where birthday = '1988-03-12';
delete from employee where name like 'Jeno%';

-- select * from employee;